# GitHub Actions docs
# https://help.github.com/en/articles/about-github-actions
# https://help.github.com/en/articles/workflow-syntax-for-github-actions
name: CI/CD

on:
  push:
    branches:    
      - master
      - main
      - try-gha

  pull_request:
    branches:
      - master
      - main

jobs:
  build:

    # Machine environment:
    # https://help.github.com/en/articles/software-in-virtual-environments-for-github-actions#ubuntu-1804-lts
    # We specify the Node.js version manually below, and use versioned Chrome from Puppeteer.
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v1
    - name: Install Latest Stable Chrome
      run: |
        curl https://dl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
        echo 'deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main' | sudo tee /etc/apt/sources.list.d/google-chrome.list
        sudo apt-get update
        sudo apt install google-chrome-stable
    - name: Use Node.js 14.17
      uses: actions/setup-node@v1
      with:
        node-version: 14.17
    - name: Install dependencies
      working-directory: ./v2
      run: yarn install
    - name: Test
      working-directory: ./v2
      run: CI=true yarn test
    # - name: Deploy
    #   if: github.ref == 'refs/heads/master'      
    #   run: npm run action:deploy -- --message `git rev-parse HEAD` 
    #   env:
    #     CI: true
    #     GH_TOKEN: ${{ secrets.GH_TOKEN }}
    # - uses: codecov/codecov-action@v1
