# GitHub Actions docs
# https://help.github.com/en/articles/about-github-actions
# https://help.github.com/en/articles/workflow-syntax-for-github-actions
name: CI/CD

on:
  push:
    branches:    
      - master
      - try-gha
      - v*.**
      - pr/*

jobs:
  build:

    # Machine environment:
    # https://help.github.com/en/articles/software-in-virtual-environments-for-github-actions#ubuntu-1804-lts
    # We specify the Node.js version manually below, and use versioned Chrome from Puppeteer.
    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v1
    - name: Install Latest Stable Chrome
      run: |
        curl https://dl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
        echo 'deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main' | sudo tee /etc/apt/sources.list.d/google-chrome.list
        sudo apt-get update
        sudo apt install google-chrome-stable
    - name: Use Node.js 12.8
      uses: actions/setup-node@v1
      with:
        node-version: 12.8
    - name: Install dependencies
      run: npm install
    - name: Lint
      run: npm run lint
    - name: Test
      run: npm run test -- --no-watch --no-progress --browsers=ChromeHeadlessCI
    - name: E2E
      run: npm run e2e -- --protractor-config=e2e/protractor-ci.conf.js
    - name: Deploy
      if: startsWith(github.ref, 'refs/heads/v')      
      run: npm run action:deploy -- --message `git rev-parse HEAD` 
      env:
        CI: true
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
